---
- name: Pull docker image
  hosts: all
  tasks:
          - name: Pull calculator docker image 
            docker_image:
                  name: prasanna33/scientificcalculator 
                  source: pull

          - name: Write command after pulling image
            shell: 'echo "finished pulling image"'

          - name: running container
            shell: docker run -id prasanna33/scientificcalculator
